name: CI/CD Build Steps

on:
  push:
    branches: [ main ,CI/CD_Plus_Spotify_PAT_addition ]
  workflow_dispatch: 

permissions:
  contents: read
  id-token: write

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: personal-website-460204
      SA_EMAIL: github-actions-deployer@personal-website-460204.iam.gserviceaccount.com
      WIF_PROVIDER: projects/175734553952/locations/global/workloadIdentityPools/github/providers/my-repo
      INSTANCE: instance-20250518-050907
      ZONE: us-central1-c

    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: SSH into VM & Upload new image
        run: |
          gcloud compute ssh "${INSTANCE}" \
            --zone="${ZONE}" \
            --quiet \
            --command="\
              ls -al; \
              pwd; \
              set -e; \
              sudo docker pull kchun510/portfolio.v3:latest && \
              sudo docker stop portfolio && \
              sudo docker rm portfolio && \
              sudo docker run \
              --restart unless-stopped \
              -p 3000:3000 \
              -v /home/itmanagekc/db_actions_prod:/app/db_actions \
              --env-file ./cred_dir/.env \
              --name portfolio \
              kchun510/portfolio.v3:latest
              "

